# 포트 번호 설정
server:
  port: 8085
  servlet:
    context-path: /zenless-calc

# 로그 레벨 설정
logging:
  level:
    org.springframework: INFO

# 스프링 설정
spring:

  datasource:
    url: jdbc:h2:mem:testdb  # 인메모리 H2 데이터베이스
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트가 끝나면 데이터베이스를 초기화
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN